name: deploy

on:
  push:
    branches: [runner-test]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build Application
        run: docker build -t api:${{ github.sha }} .

      - name: (Re)start Application
        run: |
          docker stop api || true
          docker rm api || true
          docker run -d \
            --name api \
            -p 3000:3000 \
            --restart unless-stopped \
            api:${{ github.sha }}