name: deploy

on:
  push:
    branches: [runner-test]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: build
        run: sudo docker build -t api:latest .

      - name: stop old
        run: |
          sudo docker stop api || true
          sudo docker rm api || true

      - name: run new
        run: |
          sudo docker run -d \
            --name api \
            -p 3000:3000 \
            --restart unless-stopped \
            api:latest